spring:
  data:
    mongodb:
      #username: chandan
      #password: root
      database: categoryDb
      port: 27017
      host: localhost
  application:
    name: category-service
server:
  port: 8083
